version: "3" # composeファイルのバージョン
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    tty: true # ②コンテナの永続化
    volumes:
      - ./backend:/go/src/app
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ./frontend:/frontend/src/app
    tty: true
    #command: sh -c "yarn dev"
  webServer:
    image: nginx
    depends_on:
      - backend
    container_name: webServer
    ports:
      - 80:80
    environment:
      - TZ=Asia/***REMOVED***
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
