version: "3" # composeファイルのバージョン
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    tty: true # ②コンテナの永続化
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./backend:/go/src/app
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend/src/app
    tty: true
    depends_on:
      - webServer
    #command: sh -c "yarn dev"
  webServer:
    image: nginx
    depends_on:
      - backend
    container_name: webServer
    ports:
      - 80:80
    environment:
      - TZ=Asia/***REMOVED***
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  mongo:
    build: ./docker/mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    build: ./docker/mongo_express
    restart: always
    ports:
      - 8081:8081
