version: "3" # composeファイルのバージョン
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    tty: true # ②コンテナの永続化
    volumes:
      - ./backend:/go/src/app
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend/src/app
    tty: true
    #command: sh -c "yarn dev"
  webServer:
    image: nginx
    depends_on:
      - backend
    container_name: webServer
    ports:
      - 80:80
    environment:
      - TZ=Asia/***REMOVED***
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  mysql_container:
    links:
      - backend
    build: ./docker/db
    image: mysql:5.7
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: Portfolio
      MYSQL_PASSWORD: admin123
      TZ: "Asia/***REMOVED***"
    ports:
      - 3302:3306
    expose:
      - 3306
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./log/mysql:/var/log/mysql/
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: db_container
    #networks:
    #- app-network
